// Handles language switching, mobile navigation, and footer year for the academic webpage.
const translations = {
  en: {
    nav_about: "About",
    nav_research: "Research",
    nav_education: "Education",
    nav_teaching: "Teaching",
    nav_publications: "Publications",
    nav_skills: "Skills",
    nav_contact: "Contact",
    hero_eyebrow: "PhD Researcher in Computer Science",
    hero_subtitle: "Neural information retrieval, generative retrieval, NLP, and deep learning",
    hero_summary: "I work on neural and generative information retrieval, with a focus on text-to-text architectures, document identifier generation, constrained decoding, and experimental evaluation of retrieval systems.",
    btn_contact: "Contact",
    profile_role: "PhD researcher, Université Toulouse III - Paul Sabatier",
    profile_line1: "Computer Science",
    profile_line2: "Neural and Generative IR",
    profile_line3: "Deep Learning for NLP",
    about_label: "About",
    about_title: "Academic profile",
    about_text1: "I am a PhD researcher in computer science at Université Toulouse III - Paul Sabatier. My research focuses on neural information retrieval, generative retrieval models, and text-to-text architectures for indexing and ranking.",
    about_text2: "My work investigates how documents can be represented, indexed, and retrieved using neural and generative models, including document identifiers, passage-level representations, constrained decoding, and retrieval-oriented evaluation.",
    research_label: "Research",
    research_title: "Research interests",
    research_intro1: "My research is situated at the intersection of information retrieval, natural language processing, and deep learning. I study how neural models can represent large document collections and how retrieval systems can move beyond classical keyword matching while still preserving exact-match signals that are often essential for factual, technical, and entity-centered queries. This includes work on dense retrieval, neural ranking, lexical-semantic matching, and the empirical analysis of retrieval behavior across different evaluation settings.",
    research_intro2: "A central part of my PhD work focuses on generative retrieval, where the retrieval task is formulated as a text-to-text generation problem. Instead of scoring documents only through a conventional index, the model learns to generate document identifiers or structured textual representations that point to relevant documents. I am particularly interested in the design of document identifiers, passage-level supervision, constrained decoding, multi-identifier representations, and the failure modes that appear when autoregressive decoding prunes relevant identifiers too early during inference.",
    research_intro3: "Methodologically, my work combines model design, dataset construction, large-scale training, and careful evaluation. I work with Transformer-based architectures such as T5-style models, fine-tuning pipelines, retrieval benchmarks, and metrics such as Recall@k, MRR, and nDCG. I also pay close attention to reproducibility, error analysis, statistical comparison, and the interpretation of retrieval outputs, especially when comparing generative retrieval methods with dense, sparse, or hybrid baselines.",
    research_card1_title: "Neural information retrieval",
    research_card1_text: "Study of dense retrieval and neural ranking models, including how semantic representations interact with lexical evidence, exact-match signals, query-document matching, and retrieval effectiveness across heterogeneous collections.",
    research_card2_title: "Generative retrieval",
    research_card2_text: "Text-to-text retrieval with document identifiers, structured semantic codes, constrained decoding, sequence-based indexing, and analysis of how identifier design influences memorization, generation reliability, and ranking behavior.",
    research_card3_title: "Deep learning for NLP",
    research_card3_text: "Transformer-based NLP with T5-style architectures, fine-tuning strategies, representation learning, synthetic data, language modeling, and controlled experiments for retrieval-oriented neural systems.",
    research_card4_title: "Evaluation and analysis",
    research_card4_text: "Evaluation of retrieval systems using Recall@k, MRR, nDCG, prefix-level diagnostics, error analysis, statistical testing, checkpoint comparison, and reproducible experiment pipelines.",
    education_label: "Education",
    education_title: "Education",
    edu_phd_date: "Since Oct. 2023",
    edu_phd_title: "PhD in Computer Science",
    edu_phd_place: "Université Toulouse III - Paul Sabatier",
    edu_phd_desc: "Research on information retrieval and deep learning, with emphasis on text-to-text generative retrieval models, document representations, and ranking.",
    edu_master_title: "Academic Master in Computer Science",
    edu_master_place: "École Supérieure d’Informatique d’Alger",
    edu_master_desc: "Master thesis on the transferability of dense ranking models.",
    edu_engineer_title: "State Engineering Degree in Computer Science",
    edu_engineer_place: "École Supérieure d’Informatique d’Alger",
    experience_label: "Experience",
    experience_title: "Research experience",
    exp_phd_date: "Since Oct. 2023",
    exp_phd_title: "PhD Researcher, Université Toulouse III - Paul Sabatier",
    exp_phd_1: "Design and evaluation of neural and generative information retrieval models.",
    exp_phd_2: "Study of text-to-text models for indexing, document identifier generation, and ranking.",
    exp_phd_3: "Analysis of constrained decoding and its effect on document selection during inference.",
    exp_phd_4: "Reproducible experiments covering data preparation, training, evaluation, statistical analysis, and result synthesis.",
    exp_intern_title: "Research intern, Université Toulouse III - Paul Sabatier",
    exp_intern_1: "Work on information retrieval, dense models, language modeling, and lexical-semantic matching.",
    exp_intern_2: "Study of dense ranking model transferability and comparison with exact-match signals.",
    exp_intern_3: "Experiments with bi-encoder models and retrieval performance analysis.",
    teaching_label: "Teaching",
    teaching_title: "Teaching experience",
    teaching_role: "Teaching assistant under a DCCE teaching contract, IUT Toulouse, Department of Computer Science",
    teaching_general: "Teaching activities carried out as part of a DCCE teaching contract, including preparation of practical sessions, supervision of tutorials and labs, student support, grading, assessment, and exam supervision.",
    teaching_db_title: "Databases and data management",
    teaching_db_text: "SQL, NoSQL, MongoDB, relational and non-relational data models, data organization, and data protection.",
    teaching_uml_title: "Software modeling",
    teaching_uml_text: "UML, object-oriented design, Modélio, requirements formalization, and simple software design workflows.",
    teaching_cs_title: "Computer science foundations",
    teaching_cs_text: "Programming, algorithms, data structures, object-oriented programming, and applied computer science methodology.",
    publications_label: "Publications",
    publications_title: "Publications and scientific communications",
    pub1_title: "MarkedDPR: Enhancing Dense Passage Retrieval with Exact Match Signals and Synthetic Data Augmentation.",
    pub2_title: "MarkedDPR: Un bi-encodeur exploitant la correspondance lexicale.",
    skills_label: "Skills",
    skills_title: "Scientific and technical skills",
    skills_ir_title: "Information retrieval",
    skills_ir_text: "Dense retrieval, generative retrieval, neural ranking, lexical-semantic matching, exact-match signals, document identifiers, constrained decoding, and evaluation metrics.",
    skills_nlp_title: "NLP and deep learning",
    skills_nlp_text: "Transformers, T5, text-to-text models, fine-tuning, synthetic data, PyTorch, Hugging Face, model evaluation, and experimental NLP workflows.",
    skills_programming_title: "Programming and data",
    skills_programming_text: "Python, SQL, NoSQL, MongoDB, relational and non-relational databases, database design, algorithms, data structures, and object-oriented programming.",
    skills_modeling_title: "Software modeling and design",
    skills_modeling_text: "UML, Modélio, object-oriented analysis and design, requirements formalization, class diagrams, use-case diagrams, and software design methodology.",
    skills_exp_title: "Experimentation",
    skills_exp_text: "Corpus preparation, preprocessing scripts, model training, checkpoint evaluation, Recall@k, MRR, nDCG, statistical analysis, error analysis, and result synthesis.",
    skills_compute_title: "Computing environment",
    skills_compute_text: "Linux, shell scripting, GPU-based experiments, SLURM workflows, high-performance computing environments, experiment tracking, and reproducible execution pipelines.",
    languages_label: "Languages",
    languages_title: "Languages",
    lang_fr: "French",
    lang_fr_level: "Fluent",
    lang_en: "English",
    lang_en_level: "Scientific and technical use",
    lang_ar: "Arabic",
    lang_ar_level: "Native language",
    contact_label: "Contact",
    contact_title: "Get in touch",
    contact_text: "For academic contact, research collaboration, teaching opportunities, or questions about my work, you can reach me by email or through my academic profiles.",
    scholar_link: "Profile",
    back_top: "Back to top"
  },
  fr: {
    nav_about: "Profil",
    nav_research: "Recherche",
    nav_education: "Formation",
    nav_teaching: "Enseignement",
    nav_publications: "Publications",
    nav_skills: "Compétences",
    nav_contact: "Contact",
    hero_eyebrow: "Doctorant en informatique",
    hero_subtitle: "Recherche d’information neuronale, recherche générative, NLP et apprentissage profond",
    hero_summary: "Je travaille sur la recherche d’information neuronale et générative, avec un intérêt particulier pour les architectures texte-à-texte, la génération d’identifiants documentaires, le décodage contraint et l’évaluation expérimentale des systèmes de recherche.",
    btn_contact: "Contact",
    profile_role: "Doctorant, Université Toulouse III - Paul Sabatier",
    profile_line1: "Informatique",
    profile_line2: "Recherche d’information neuronale et générative",
    profile_line3: "Apprentissage profond pour le NLP",
    about_label: "Profil",
    about_title: "Profil académique",
    about_text1: "Je suis doctorant en informatique à l’Université Toulouse III - Paul Sabatier. Mes travaux portent sur la recherche d’information neuronale, les modèles génératifs de recherche et les architectures texte-à-texte pour l’indexation et le ranking.",
    about_text2: "Mes recherches étudient la représentation, l’indexation et la récupération des documents à l’aide de modèles neuronaux et génératifs, notamment les identifiants documentaires, les représentations au niveau passage, le décodage contraint et l’évaluation orientée recherche d’information.",
    research_label: "Recherche",
    research_title: "Domaines de recherche",
    research_intro1: "Mes recherches se situent à l’intersection de la recherche d’information, du traitement automatique des langues et de l’apprentissage profond. J’étudie la manière dont les modèles neuronaux peuvent représenter de grandes collections documentaires et comment les systèmes de recherche peuvent dépasser l’appariement strictement lexical tout en conservant les signaux d’appariement exact, qui restent importants pour les requêtes factuelles, techniques ou centrées sur des entités. Cela inclut le dense retrieval, le ranking neuronal, l’appariement lexical et sémantique, ainsi que l’analyse empirique du comportement des systèmes de recherche.",
    research_intro2: "Une partie centrale de ma thèse porte sur la recherche d’information générative, où la récupération de documents est formulée comme un problème de génération texte-à-texte. Au lieu de seulement scorer les documents à partir d’un index classique, le modèle apprend à générer des identifiants documentaires ou des représentations textuelles structurées qui renvoient vers les documents pertinents. Je m’intéresse en particulier à la conception des identifiants, à la supervision au niveau passage, au décodage contraint, aux représentations multi-identifiants et aux cas d’échec où le décodage autorégressif élimine trop tôt des identifiants pertinents pendant l’inférence.",
    research_intro3: "Sur le plan méthodologique, mon travail combine conception de modèles, construction de jeux de données, entraînement à grande échelle et évaluation détaillée. J’utilise des architectures de type Transformer, notamment des modèles de style T5, des pipelines de fine-tuning, des benchmarks de recherche d’information et des métriques comme Recall@k, MRR et nDCG. J’accorde aussi une attention importante à la reproductibilité, à l’analyse des erreurs, à la comparaison statistique et à l’interprétation des sorties de recherche, notamment lorsque les méthodes génératives sont comparées à des approches denses, lexicales ou hybrides.",
    research_card1_title: "Recherche d’information neuronale",
    research_card1_text: "Étude des modèles de dense retrieval et de ranking neuronal, avec un intérêt pour l’interaction entre représentations sémantiques, signaux lexicaux, appariement exact et efficacité de recherche sur des collections hétérogènes.",
    research_card2_title: "Recherche d’information générative",
    research_card2_text: "Recherche texte-à-texte avec identifiants documentaires, codes sémantiques structurés, décodage contraint, indexation séquentielle et analyse de l’effet du design des identifiants sur la mémorisation, la fiabilité de génération et le ranking.",
    research_card3_title: "Apprentissage profond pour le NLP",
    research_card3_text: "NLP fondé sur les Transformers, modèles de type T5, stratégies de fine-tuning, apprentissage de représentations, données synthétiques, language modeling et expériences contrôlées pour les systèmes de recherche neuronaux.",
    research_card4_title: "Évaluation et analyse",
    research_card4_text: "Évaluation de systèmes de recherche avec Recall@k, MRR, nDCG, diagnostics au niveau préfixe, analyse des erreurs, tests statistiques, comparaison de checkpoints et pipelines expérimentaux reproductibles.",
    education_label: "Formation",
    education_title: "Formation",
    edu_phd_date: "Depuis oct. 2023",
    edu_phd_title: "Doctorat en informatique",
    edu_phd_place: "Université Toulouse III - Paul Sabatier",
    edu_phd_desc: "Recherche sur la recherche d’information et l’apprentissage profond, avec un accent sur les modèles génératifs texte-à-texte, les représentations documentaires et le ranking.",
    edu_master_title: "Master académique en informatique",
    edu_master_place: "École Supérieure d’Informatique d’Alger",
    edu_master_desc: "Mémoire sur la transférabilité des modèles denses de ranking.",
    edu_engineer_title: "Diplôme d’ingénieur d’État en informatique",
    edu_engineer_place: "École Supérieure d’Informatique d’Alger",
    experience_label: "Expérience",
    experience_title: "Expérience de recherche",
    exp_phd_date: "Depuis oct. 2023",
    exp_phd_title: "Doctorant, Université Toulouse III - Paul Sabatier",
    exp_phd_1: "Conception et évaluation de modèles de recherche d’information neuronale et générative.",
    exp_phd_2: "Étude de modèles texte-à-texte pour l’indexation, la génération d’identifiants et le ranking de documents.",
    exp_phd_3: "Analyse du décodage contraint et de ses effets sur la sélection des documents lors de l’inférence.",
    exp_phd_4: "Expériences reproductibles couvrant la préparation des données, l’entraînement, l’évaluation, l’analyse statistique et la synthèse des résultats.",
    exp_intern_title: "Stagiaire de recherche, Université Toulouse III - Paul Sabatier",
    exp_intern_1: "Travail sur la recherche d’information, les modèles denses, le language modeling et l’appariement lexical et sémantique.",
    exp_intern_2: "Étude de la transférabilité des modèles denses de ranking et comparaison avec des signaux d’appariement exact.",
    exp_intern_3: "Expérimentation sur des modèles bi-encodeurs et analyse des performances de retrieval.",
    teaching_label: "Enseignement",
    teaching_title: "Expérience d’enseignement",
    teaching_role: "Chargé d’enseignement sous contrat DCCE, IUT Toulouse, Département Informatique",
    teaching_general: "Activités d’enseignement réalisées dans le cadre d’un contrat DCCE, incluant la préparation de travaux pratiques, l’animation de TD/TP, l’accompagnement des étudiants, la correction, l’évaluation et la surveillance d’examens.",
    teaching_db_title: "Bases de données et gestion des données",
    teaching_db_text: "SQL, NoSQL, MongoDB, modèles relationnels et non relationnels, organisation des données et protection des données.",
    teaching_uml_title: "Modélisation logicielle",
    teaching_uml_text: "UML, conception orientée objet, Modélio, formalisation des besoins et démarches simples de conception logicielle.",
    teaching_cs_title: "Fondements de l’informatique",
    teaching_cs_text: "Programmation, algorithmique, structures de données, programmation orientée objet et méthodologie informatique appliquée.",
    publications_label: "Publications",
    publications_title: "Publications et communications scientifiques",
    pub1_title: "MarkedDPR: Enhancing Dense Passage Retrieval with Exact Match Signals and Synthetic Data Augmentation.",
    pub2_title: "MarkedDPR: Un bi-encodeur exploitant la correspondance lexicale.",
    skills_label: "Compétences",
    skills_title: "Compétences scientifiques et techniques",
    skills_ir_title: "Recherche d’information",
    skills_ir_text: "Dense retrieval, generative retrieval, ranking neuronal, appariement lexical et sémantique, signaux d’appariement exact, identifiants documentaires, décodage contraint et métriques d’évaluation.",
    skills_nlp_title: "NLP et apprentissage profond",
    skills_nlp_text: "Transformers, T5, modèles texte-à-texte, fine-tuning, données synthétiques, PyTorch, Hugging Face, évaluation de modèles et workflows expérimentaux en NLP.",
    skills_programming_title: "Programmation et données",
    skills_programming_text: "Python, SQL, NoSQL, MongoDB, bases relationnelles et non relationnelles, conception de bases de données, algorithmique, structures de données et programmation orientée objet.",
    skills_modeling_title: "Modélisation et conception logicielle",
    skills_modeling_text: "UML, Modélio, analyse et conception orientées objet, formalisation des besoins, diagrammes de classes, diagrammes de cas d’utilisation et méthodologie de conception logicielle.",
    skills_exp_title: "Expérimentation",
    skills_exp_text: "Préparation de corpus, scripts de prétraitement, entraînement de modèles, évaluation de checkpoints, Recall@k, MRR, nDCG, analyse statistique, analyse des erreurs et synthèse des résultats.",
    skills_compute_title: "Environnement de calcul",
    skills_compute_text: "Linux, scripts shell, expérimentations GPU, workflows SLURM, environnements de calcul haute performance, suivi d’expériences et pipelines d’exécution reproductibles.",
    languages_label: "Langues",
    languages_title: "Langues",
    lang_fr: "Français",
    lang_fr_level: "Courant",
    lang_en: "Anglais",
    lang_en_level: "Usage scientifique et technique",
    lang_ar: "Arabe",
    lang_ar_level: "Langue maternelle",
    contact_label: "Contact",
    contact_title: "Me contacter",
    contact_text: "Pour un contact académique, une collaboration de recherche, une opportunité d’enseignement ou une question sur mes travaux, vous pouvez me contacter par email ou consulter mes profils académiques.",
    scholar_link: "Profil",
    back_top: "Retour en haut"
  }
};

const applyLanguage = (lang) => {
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      element.textContent = translations[lang][key];
    }
  });
  document.querySelectorAll(".lang-btn").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });
  localStorage.setItem("preferred-language", lang);
};

document.querySelectorAll(".lang-btn").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

const menuToggle = document.querySelector(".menu-toggle");
const navLinks = document.querySelector("#navLinks");

menuToggle.addEventListener("click", () => {
  const isOpen = navLinks.classList.toggle("open");
  menuToggle.setAttribute("aria-expanded", String(isOpen));
});

navLinks.querySelectorAll("a").forEach((link) => {
  link.addEventListener("click", () => {
    navLinks.classList.remove("open");
    menuToggle.setAttribute("aria-expanded", "false");
  });
});

document.querySelector("#year").textContent = new Date().getFullYear();

applyLanguage(localStorage.getItem("preferred-language") || "en");
